      # Warning: indentation here matters!

      # Pytorch MacOS builds
      - pytorch_macos_10_13_py3_build:
          requires:
            - setup
          filters:
            branches:
              only: master
      - pytorch_macos_10_13_py3_test:
          requires:
            - setup
            - pytorch_macos_10_13_py3_build
          filters:
            branches:
              only: master
      - pytorch_macos_10_13_cuda9_2_cudnn7_py3_build:
          requires:
            - setup
